CREATE SCHEMA tienda_de_abarrotes;
USE tienda_de_abarrotes;
CREATE TABLE productos(id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id));
ALTER TABLE productos ADD COLUMN nombre VARCHAR(255) NOT NULL;
ALTER TABLE productos ADD COLUMN nombre VARCHAR(255) NOT NULL;
ALTER TABLE productos ADD COLUMN nombre VARCHAR(255) NOT NULL;
ALTER TABLE productos ADD COLUMN nombre VARCHAR(255) NOT NULL;



CREATE TABLE proveedores(id INT NOT NULL AUTO_INCREMENT);
CREATE TABLE consumidores(id INT NOT NULL AUTO_INCREMENT);